name: Go
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Check out code
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go mod tidy

      - name: Build frontend
        run: cd frontend && yarn install && yarn build

      - name: Build binary
        run: |
          CGO_ENABLED=0 go build -v -trimpath -ldflags "-w -s -extldflags '-static' -X 'github.com/wuhan005/Scrooge.CommitSHA=$GITHUB_SHA'" -o Scrooge .

      - name: Copy binary
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "Scrooge"
          target: "/home/ubuntu/scrooge/"

      - name: Restart service
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          connect_timeout: 10s
          script: |
            sudo service scrooge restart